[metadata]
name = "staticcheck"
description = "Go static analysis tool"
homepage = "https://staticcheck.dev/"
version_format = "semver"

[version]
source = "goproxy"
module = "honnef.co/go/tools"

[[steps]]
action = "go_install"
module = "honnef.co/go/tools"
executables = ["staticcheck"]

[verify]
command = "staticcheck --version"
pattern = "{version}"
