[metadata]
name = "nomad"
description = "Workload orchestrator"
homepage = "https://www.nomadproject.io/"
version_format = "semver"

[version]
github_repo = "hashicorp/nomad"

[[steps]]
action = "download"
url = "https://releases.hashicorp.com/nomad/{{.Version}}/nomad_{{.Version}}_{{.OS}}_{{.Arch}}.zip"

[[steps]]
action = "extract"
archive = "nomad_{{.Version}}_{{.OS}}_{{.Arch}}.zip"
format = "zip"

[[steps]]
action = "chmod"
files = ["nomad"]

[[steps]]
action = "install_binaries"
binaries = ["nomad"]

[verify]
command = "nomad version"
pattern = "{version}"
