[metadata]
name = "packer"
description = "Build automated machine images"
homepage = "https://www.packer.io/"
version_format = "semver"

[version]
github_repo = "hashicorp/packer"

[[steps]]
action = "download"
url = "https://releases.hashicorp.com/packer/{{.Version}}/packer_{{.Version}}_{{.OS}}_{{.Arch}}.zip"

[[steps]]
action = "extract"
archive = "packer_{{.Version}}_{{.OS}}_{{.Arch}}.zip"
format = "zip"

[[steps]]
action = "chmod"
files = ["packer"]

[[steps]]
action = "install_binaries"
binaries = ["packer"]

[verify]
command = "packer version"
pattern = "{version}"
