[metadata]
name = "pkg-config"
description = "Helper tool for compile and link flags for libraries"
homepage = "https://www.freedesktop.org/wiki/Software/pkg-config/"
binaries = ["bin/pkg-config"]

[version]
source = "homebrew"
formula = "pkgconf"

[[steps]]
action = "homebrew"
formula = "pkgconf"

[[steps]]
action = "install_binaries"
install_mode = "directory"
binaries = ["bin/pkg-config"]

[verify]
command = "pkg-config --version"
pattern = "{version}"
