[metadata]
name = "boundary"
description = "Secure remote access"
homepage = "https://www.boundaryproject.io/"
version_format = "semver"

[version]
github_repo = "hashicorp/boundary"

[[steps]]
action = "download"
url = "https://releases.hashicorp.com/boundary/{{.Version}}/boundary_{{.Version}}_{{.OS}}_{{.Arch}}.zip"

[[steps]]
action = "extract"
format = "zip"

[[steps]]
action = "chmod"
files = ["boundary"]

[[steps]]
action = "install_binaries"
binaries = ["boundary"]

[verify]
command = "boundary version"
pattern = "{version}"
