[metadata]
name = "zig"
description = "General-purpose programming language and toolchain"
homepage = "https://ziglang.org/"
version_format = "semver"

[version]
github_repo = "ziglang/zig"

[[steps]]
action = "download_archive"
url = "https://ziglang.org/download/{version}/zig-{arch}-{os}-{version}.tar.xz"
archive_format = "tar.xz"
strip_dirs = 1
binaries = ["zig"]
os_mapping = { darwin = "macos", linux = "linux" }
arch_mapping = { amd64 = "x86_64", arm64 = "aarch64" }

[verify]
command = "zig version"
pattern = "{version}"
