[metadata]
name = "waypoint"
description = "Build deploy and release across platforms"
homepage = "https://www.waypointproject.io/"
version_format = "semver"

[version]
github_repo = "hashicorp/waypoint"

[[steps]]
action = "download"
url = "https://releases.hashicorp.com/waypoint/{{.Version}}/waypoint_{{.Version}}_{{.OS}}_{{.Arch}}.zip"

[[steps]]
action = "extract"
format = "zip"

[[steps]]
action = "chmod"
files = ["waypoint"]

[[steps]]
action = "install_binaries"
binaries = ["waypoint"]

[verify]
command = "waypoint version"
pattern = "{version}"
