[metadata]
name = "vault"
description = "Secrets management"
homepage = "https://www.vaultproject.io/"
version_format = "semver"

[version]
github_repo = "hashicorp/vault"

[[steps]]
action = "download"
url = "https://releases.hashicorp.com/vault/{{.Version}}/vault_{{.Version}}_{{.OS}}_{{.Arch}}.zip"

[[steps]]
action = "extract"
archive = "vault_{{.Version}}_{{.OS}}_{{.Arch}}.zip"
format = "zip"

[[steps]]
action = "chmod"
files = ["vault"]

[[steps]]
action = "install_binaries"
binaries = ["vault"]

[verify]
command = "vault version"
pattern = "{version}"
